### PR TITLE
Fix output of the convert command

### LINKED ISSUE #186: Convert command returns 0 when the converted value is too small
We use `Number.toFixed(2)` so smaller results like 0.001 will be displayed as 0. We need to adjust the precision to provide more accurate conversions

### PR DESCRIPTION
**Pull request by mushroom-disaster**
I got around the issue by dynamically setting the precision of `toFixed()` depending on how many zeroes are present after the decimal point in the result. So if there are three zeroes after the decimal point, the precision would be two more than that.
Fixes #186

### CODE REVIEW

File: src/bot/commands/misc/convert.js [hunk 1]
```diff
@@ -27,12 +27,50 @@ async function fetchLatestRates () {
...
+ * @returns {number} Number of fraction digits
+ */
+function getFractionDigits (value) {
+	const numberOfZeroes = getCountOfZeroesAfterDecimalPoint(value);
+
+	let fractionDigits = 2;
+	if (numberOfZeroes > 0) {
+		fractionDigits = numberOfZeroes + 2;
+	}
+	// Since toFixed doesn't accept values greater than 20
```
Comment (eritbh) [inline src/bot/commands/misc/convert.js:69]: Interesting, didn't know this. Is this documented somewhere? Mind linking it if you have it handy?

File: src/bot/commands/misc/convert.js [hunk 2]
```diff
@@ -27,12 +27,50 @@ async function fetchLatestRates () {
...
+ * @param {number} value
+ * @returns {number} Number of fraction digits
+ */
+function getFractionDigits (value) {
+	const numberOfZeroes = getCountOfZeroesAfterDecimalPoint(value);
+
+	let fractionDigits = 2;
+	if (numberOfZeroes > 0) {
+		fractionDigits = numberOfZeroes + 2;
+	}
```
Comment (eritbh) [inline src/bot/commands/misc/convert.js:68]: Does this imply that whole number results will be rendered with 2 trailing zeroes no matter what (e.g. `1234.00`)? Is that desirable?

File: src/bot/commands/misc/convert.js [hunk 3]
```diff
@@ -27,12 +27,50 @@ async function fetchLatestRates () {
...
+	let fractionalPart = value % 1;
+	let numberOfZeroes = -1;
+
+	while (fractionalPart < 1 && fractionalPart > 0) {
+		fractionalPart *= 10;
+		numberOfZeroes++;
+	}
+	numberOfZeroes = Math.max(0, numberOfZeroes);
+
+	return numberOfZeroes;
```
Comment (eritbh) [inline src/bot/commands/misc/convert.js:54]: I'd probably simplify this to just `return` the `Math.max` expression rather than doing another assignment:
```suggestion
	return Math.max(0, numberOfZeroes);
```

File: src/bot/commands/misc/convert.js [hunk 4]
```diff
@@ -27,12 +27,50 @@ async function fetchLatestRates () {
...
+	return `${baseValue.toString()}${baseType} is equal to ${conversion.toFixed(fractionDigits)}${targetType}`;
+}
+
+/**
+ * Gets the count of zeroes after the decimal point but before a non-zero number
+ * @param {number} value
+ * @returns {number} Number of zeroes
+ */
+function getCountOfZeroesAfterDecimalPoint (value) {
+	let fractionalPart = value % 1;
```
Comment (eritbh) [inline src/bot/commands/misc/convert.js:45]: This is clever, I never knew this trick!

**Review by eritbh — COMMENTED** [review]
Thanks, just a couple nits and questions below.

Also, can you toss "Fixes #186" in the description of the PR real quick? Using that format means the issue will automatically be closed out when the PR is merged.

File: src/bot/commands/misc/convert.js (hunk 2 above)
Comment (mushroom-disaster) [reply src/bot/commands/misc/convert.js:68]: > Does this imply that whole number results will be rendered with 2 trailing zeroes no matter what (e.g. `1234.00`)? Is that desirable?

Yeah, it would. But that was the behaviour before anyway

File: src/bot/commands/misc/convert.js (hunk 1 above)
Comment (mushroom-disaster) [reply src/bot/commands/misc/convert.js:69]: [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed)

> The number of digits to appear after the decimal point; this may be a value between 0 and 20, inclusive, and implementations may optionally support a larger range of values. If this argument is omitted, it is treated as 0

File: src/bot/commands/misc/convert.js (hunk 2 above)
Comment (mushroom-disaster) [reply src/bot/commands/misc/convert.js:68]: I could get around this by checking if there any non-zero numbers after the decimal point and if there aren't just setting it to 0

File: src/bot/commands/misc/convert.js (hunk 4 above)
Comment (mushroom-disaster) [reply src/bot/commands/misc/convert.js:45]: Yeah, I got it from a stackoverflow answer

File: src/bot/commands/misc/convert.js (hunk 2 above)
Comment (eritbh) [reply src/bot/commands/misc/convert.js:68]: I didn't realize this before, but I think with this code it'll always be 2 more than necessary, e.g. something like `12.5` would render as `12.500`. That's fine with me - I was concerned that it was going to do something inconsistent with whole numbers, but I just didn't read the code well enough. I don't really care whether we render trailing zeroes or not, go with whatever you think is clearer for the output.

Unrelated - looking at it again, these `if` statements could probably just be a couple `Math` calls:

```js
return Math.max(2, Math.min(numberOfZeroes + 2, 20));
```

JS doesn't really have a good clamp function built in, but I've seen chaining `max` and `min` like this in a handful of contexts so I think it might be a bit cleaner this way. I don't have a super strong preference though; if you think doing it with `if` statements is more readable, then we can keep your version.

Comment (mushroom-disaster) [reply src/bot/commands/misc/convert.js:66]: `12.5` would be `12.50` yes. There would be an extra zero for numbers like this. I'll try your suggestion!

Comment (mushroom-disaster) [reply src/bot/commands/misc/convert.js]: @eritbh I used your suggestion. It works. I already pushed the changes

**Review by eritbh — APPROVED** [review]
LGTM, merge whenever!
